#!/usr/bin/env node
// verify/run.mjs
// ─────────────────────────────────────────────────────────────────────────────
// ALKI — Sprint-fix verification runner.
//
//   node verify/run.mjs              # data-checks + e2e, full report + JSON
//   node verify/run.mjs --data-only  # skip the browser layer
//
// Prints the git commit/tree it tested (so results map to the code with the
// fixes, NOT prod, which may lag), runs the static data-checks and the
// Playwright e2e specs, prints a report grouped by sprint, and writes:
//   • verify-report.json     — array of {feedback_id, sprint, check, result, detail, tested_commit}
//   • verify/MANUAL_CHECKLIST.md — regenerated human-only checklist
//
// Result buckets: PASS (machine-verified) | FAIL (claimed fixed, isn't) |
//                 MANUAL (human-only) | BLOCKED (couldn't reach state to judge).
// Writes NOTHING to the feedback table.
// ─────────────────────────────────────────────────────────────────────────────

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

import { runDataChecks } from "./data-checks.mjs";
import { ROOT, BASE_URL, gitTree, ensureServer, killTree } from "./e2e/_harness.mjs";
import { run as runJourney } from "./e2e/journey.spec.mjs";
import { run as runSettingsQA } from "./e2e/settings-qa.spec.mjs";
import { run as runAdmin } from "./e2e/admin.spec.mjs";
import { run as runRls } from "./e2e/rls.spec.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SHOT_DIR = path.join(__dirname, "screenshots");
const DATA_ONLY = process.argv.includes("--data-only");

// Visual-only / external checks a machine cannot honestly judge — these are
// authored into the manual checklist regardless of the e2e run.
const STATIC_MANUAL = [
  { feedback_id: "8096d2f6", sprint: "Avatar", check: "Athletic clothing renders correctly across ALL 3 avatar render sites (home hero, switcher, projection)", note: "Visually confirm shirt/sports-bra + shorts draw correctly on the 2D SVG AND 3D avatars at every site." },
  { feedback_id: "fa9dcbfe", sprint: "Avatar", check: "A 185lb vs a 285lb profile actually look different on the avatar", note: "Never code-fixed — was 'verify only'. Create two eidolons (185lb / 285lb, same height) and confirm the bodies read visibly different." },
  { feedback_id: "1.4", sprint: "Auth", check: "Password-reset email round-trip works end-to-end", note: "Trigger 'forgot password', receive the email, confirm the link lands on the deployed app (NEXT_PUBLIC_SITE_URL) and lets you set a new password — not a Supabase bypass." },
];

function group(rows) {
  const m = new Map();
  for (const r of rows) { if (!m.has(r.sprint)) m.set(r.sprint, []); m.get(r.sprint).push(r); }
  return m;
}
const ICON = { PASS: "✅", FAIL: "❌", MANUAL: "📝", BLOCKED: "⛔" };
const ORDER = { FAIL: 0, BLOCKED: 1, MANUAL: 2, PASS: 3 };

function printReport(rows, tree) {
  console.log("\n══════════════════════════════════════════════════════════════");
  console.log("  ALKI — SPRINT-FIX VERIFICATION REPORT");
  console.log(`  tested commit: ${tree.sha}${tree.dirty ? "  (working tree DIRTY — uncommitted changes present)" : "  (clean tree)"}`);
  console.log(`  base url: ${BASE_URL}`);
  console.log("══════════════════════════════════════════════════════════════");
  for (const [sprint, items] of group(rows)) {
    console.log(`\n▸ ${sprint}`);
    for (const r of [...items].sort((a, b) => ORDER[a.result] - ORDER[b.result])) {
      console.log(`   ${ICON[r.result] || "  "} [${r.result.padEnd(7)}] (${r.feedback_id}) ${r.check}`);
      if (r.result !== "PASS") console.log(`              ↳ ${r.detail}`);
    }
  }
  const tally = rows.reduce((a, r) => (a[r.result] = (a[r.result] || 0) + 1, a), {});
  console.log("\n──────────────────────────────────────────────────────────────");
  console.log(`  TOTAL: ${rows.length}   ✅ PASS ${tally.PASS || 0}   ❌ FAIL ${tally.FAIL || 0}   📝 MANUAL ${tally.MANUAL || 0}   ⛔ BLOCKED ${tally.BLOCKED || 0}`);
  console.log("──────────────────────────────────────────────────────────────");
  if (tally.FAIL) {
    console.log("\n  ❌ FAILURES (claimed fixed but verification says otherwise):");
    for (const r of rows.filter(r => r.result === "FAIL")) console.log(`     • (${r.feedback_id}) ${r.check}`);
  }
  return tally;
}

function writeManualChecklist(rows, tree) {
  const manual = rows.filter(r => r.result === "MANUAL");
  const blocked = rows.filter(r => r.result === "BLOCKED");
  const lines = [];
  lines.push("# ALKI — Manual Verification Checklist");
  lines.push("");
  lines.push("> Generated by `verify/run.mjs`. These are the things a machine cannot honestly");
  lines.push("> sign off — visual rendering, multi-account behaviour, and email round-trips.");
  lines.push("> Each is a real check: tick it only after you (or Austin) confirm it on a device.");
  lines.push("");
  lines.push(`Tested commit: \`${tree.sha}\`${tree.dirty ? " (working tree dirty)" : ""}`);
  lines.push("");
  lines.push("## Visual / external (machine cannot judge)");
  lines.push("");
  for (const m of STATIC_MANUAL) {
    lines.push(`- [ ] **(${m.feedback_id}) ${m.check}**`);
    lines.push(`      ${m.note}`);
  }
  lines.push("");
  lines.push("## Flagged MANUAL by the automated run");
  lines.push("");
  if (manual.length === 0) lines.push("- _(none this run)_");
  for (const r of manual) {
    lines.push(`- [ ] **(${r.feedback_id}) ${r.check}** — _${r.sprint}_`);
    lines.push(`      ${r.detail}`);
  }
  lines.push("");
  lines.push("## BLOCKED this run (couldn't reach the UI state — re-run or check by hand)");
  lines.push("");
  if (blocked.length === 0) lines.push("- _(none this run — every check reached its state)_");
  for (const r of blocked) {
    lines.push(`- [ ] **(${r.feedback_id}) ${r.check}** — _${r.sprint}_`);
    lines.push(`      ${r.detail}`);
  }
  lines.push("");
  const p = path.join(__dirname, "MANUAL_CHECKLIST.md");
  writeFileSync(p, lines.join("\n"), "utf8");
  console.log(`\n  manual checklist → ${path.relative(ROOT, p)}`);
}

async function main() {
  const tree = gitTree();
  mkdirSync(SHOT_DIR, { recursive: true });
  const all = [];

  // ── 1) static data-checks ───────────────────────────────────────────────
  console.log("verify: running static data-checks…");
  try { all.push(...await runDataChecks()); }
  catch (e) { all.push({ feedback_id: "data-checks", sprint: "Compound data unification", check: "data-checks harness", result: "BLOCKED", detail: `data-checks crashed: ${e.message}` }); }

  // ── 2) e2e specs ─────────────────────────────────────────────────────────
  if (!DATA_ONLY) {
    const owned = await ensureServer();
    if (owned === undefined) {
      all.push({ feedback_id: "e2e", sprint: "Builder UX", check: "Playwright e2e harness", result: "BLOCKED", detail: `Could not reach or start a server at ${BASE_URL}. Run "npm run dev" (or build + start) and re-run.` });
    } else {
      let browser;
      try {
        browser = await chromium.launch({ headless: true });
        const mkShot = (ctxName) => async (page, label) => {
          const file = path.join(SHOT_DIR, `${ctxName}-${label}.png`.replace(/[^a-z0-9_.-]+/gi, "_"));
          try { await page.screenshot({ path: file, fullPage: true }); return path.relative(ROOT, file); } catch { return null; }
        };
        const specs = [
          ["journey", runJourney],
          ["settings-qa", runSettingsQA],
          ["admin", runAdmin],
          ["rls", runRls],
        ];
        for (const [name, fn] of specs) {
          console.log(`verify: e2e › ${name}…`);
          const context = await browser.newContext({ viewport: { width: 390, height: 844 } }); // mobile
          try { all.push(...await fn(context, mkShot(name))); }
          catch (e) { all.push({ feedback_id: name, sprint: "Builder UX", check: `e2e spec "${name}"`, result: "BLOCKED", detail: `spec crashed: ${e.message}` }); }
          finally { await context.close().catch(() => {}); }
        }
      } finally {
        if (browser) await browser.close().catch(() => {});
        if (owned) killTree(owned);
      }
    }
  } else {
    console.log("verify: --data-only — skipping e2e layer.");
  }

  // ── 3) report + artifacts ────────────────────────────────────────────────
  const tally = printReport(all, tree);
  const json = all.map(r => ({ ...r, tested_commit: tree.sha, tested_dirty: tree.dirty }));
  const jsonPath = path.join(ROOT, "verify-report.json");
  writeFileSync(jsonPath, JSON.stringify(json, null, 2), "utf8");
  console.log(`  report json   → ${path.relative(ROOT, jsonPath)}  (${json.length} rows)`);
  writeManualChecklist(all, tree);

  // Exit non-zero only on real FAILs (claimed-fixed-but-broken / confirmed
  // regressions). MANUAL/BLOCKED do not fail the gate — they are "go look".
  process.exit((tally.FAIL || 0) > 0 ? 1 : 0);
}

main().catch(e => { console.error("verify: fatal —", e?.stack || e); process.exit(2); });
